version: '3.9'

services:

    nginx:
        build:
            context: ./nginx
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-nginx
        working_dir: /var/www/app
        environment:
            - VIRTUAL_HOST=${DOMAIN}
        depends_on:
            - php
        volumes:
            ###> NGINX VOLUMES
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-enabled/app.conf:/etc/nginx/sites-enabled/${CONTAINER_NAME:-unnamed}.conf
            - ./nginx/logs/access.log:/var/log/nginx/access.log
            - ./nginx/logs/error.log:/var/log/nginx/error.log
            ###> TIMEZONE VOLUMES
            - /etc/localtime:/etc/localtime:ro
            ###> PROJECT VOLUME ###
            - ${PROJECT_PATH:-../}:/var/www/app
        networks:
            - frontend
            - backend
            - rabbitmq

    php:
        build:
            context: ./php
            args:
                PHP: ${PHP_VERSION}
                NAME: ${CONTAINER_NAME:-unnamed}
        user: 1000:1000
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-php
        working_dir: /var/www/app
        stdin_open: true
        tty: true
        entrypoint:
            - /bin/bash
            - /init.sh
            - ${APP_ENV:-dev}
        environment:
            ### PHP ENV ###
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
            - VIRTUAL_PROTO=fastcgi
            ###> BASH COLORS ###
            - TERM=xterm-256color
            - PS1=${PS1}
        volumes:
            ###> BASH VOLUMES ###
            - ./bash/.bash_aliases:/home/${USER}/.bash_aliases
            - ./bash/.bash_history:/root/.bash_history
            - ./bash/.bashrc:/home/${USER}/.bashrc
            - ./bash/init.sh:/init.sh
            ###> COMPOSER VOLUMES ###
            - ${COMPOSER_CONFIG_PATH:-./composer/.config}:/.composer
            - ${COMPOSER_CACHE_PATH:-./composer/.cache}:/.cache/composer
            ###> YARN VOLUMES ###
            - ${YARNRC_PATH:-./yarn/.yarnrc}:/home/${USER}/.yarnrc
            - ${YARN_CACHE_PATH:-./yarn/.config}:/home/${USER}/.cache
            - ${YARN_PATH:-./yarn}:/home/${USER}/.yarn
            ###> DOCKER USER VOLUMES
            - /home/${USER}/.ssh:/home/${USER}/.ssh:rw
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
            - /etc/shadow:/etc/shadow:ro
            ###> TIMEZONE VOLUMES
            - /etc/localtime:/etc/localtime:ro
            ###> PHP INI VOLUME
            - ./php/php.ini:/usr/local/etc/php/conf.d/custom.php.ini
            ###> PROJECT VOLUME ###
            - ${PROJECT_PATH:-../}:/var/www/app
        networks:
            - sql
            - backend
            - rabbitmq

    rabbitmq:
        image: rabbitmq:management
        container_name: ${CONTAINER_NAME:-unnamed}-rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - rabbitmq

networks:
    backend:
        driver: bridge
        name: ${CONTAINER_NAME:-unnamed}_backend_network

    frontend:
        name: ${PROXY_NETWORK_NAME:-docker_engine_proxy}
        external: true

    sql:
        name: ${SQL_NETWORK_NAME:-docker_engine_sql}
        external: true

    rabbitmq:
        driver: bridge
        name: ${CONTAINER_NAME:-unnamed}_rabbitmq_network